- name: install and start apache2
  hosts: pod-tes-managed1
  become: true

  tasks:
          - name: apache2 package is present
            apt:
                    name: apache2
                    state: present
                    update_cache: yes
                    force_apt_get: yes
                    
          - name: restart apache2 service
            service: name=apache2 state=restarted enabled=yes

          - name: copy index.html
            template: src=tes.html.j2 dest=/var/www/html/tes.html
